Add commits page styling
Tindev/Tindev-site pull request #12
Opened 2017-03-30 14:30 UTC by TimvdLippe

This adds the styling for the data that @mpasterkamp retrieves.

2017-03-31 07:28 UTC, GijsWeterings requested changes

2017-03-31 07:28 UTC, GijsWeterings commented on src/tindev-commits.html
> +      url="https://api.github.com/repos/polymer/polymer/commits/3d054bab6645421878598d26498a9f2a47804b5d"
You still hardcoded this commit ;)

2017-03-31 07:40 UTC, TimvdLippe commented on src/tindev-commits.html
> +      url="https://api.github.com/repos/polymer/polymer/commits/3d054bab6645421878598d26498a9f2a47804b5d"
Yes, for now. Still waiting on @mpasterkamp to finish the import, such that we can hook `es-query` into it.

2017-04-03 12:48 UTC, TimvdLippe commented
This is now ready for merging. The actual updating has to be done after @clanghout finished his model update work

2017-04-05 09:48 UTC, clanghout approved these changes

2017-04-05 10:43 UTC, GijsWeterings requested changes

2017-04-05 10:43 UTC, GijsWeterings commented on src/es-query.html
> +          return baseDomain + path + '/' + type + '?size=100&q=' + this._stringifyQComponents(q);
why would we include `GET` in the url?

2017-04-05 10:43 UTC, GijsWeterings commented on src/tindev-commits.html
> +        --star-color: #231657;
unused

2017-04-05 11:50 UTC, TimvdLippe commented
@GijsWeterings Fixed :smile:

2017-04-05 11:51 UTC, GijsWeterings approved these changes

2017-04-05 11:51 UTC, merged